### ISSUE TITLE
entsoe und include_second_day abort

### ISSUE THREAD

**Issue by ckvsoft** [christian1980nrw/Spotmarket-Switcher#106]
Wenn bei Entsoe keine Preise für Morgen gibt wird abgebrochen und nicht wie bei aWATTar ohne diese Preise weiter gemacht.
Tibber kann ich nicht sagen wie sich der verhält, da waren Preise da.

Das schlechte bei so einen Abbruch ist das alles was läuft weiter läuft.

Vielleicht kannst Du das checken. Ich bin zwar schon Munter weil ich MotoGP schau komme aber wahrscheinlich erst wieder am Nachmittag dazu mir was anzuschauen. 

Ich habe sicherheitshalber einen älteren code getestet, der macht das auch. Nur um sicher zu gehen das ich da nix vermurkst habe als ich den Code umsortiert habe. (aktuelles dev)

lg Chris

**Comment by ckvsoft** [comment]
I: File '/tmp/tibber_tomorrow_prices_sorted.txt' has no tomorrow data, we have to try it again until the new prices are online.

Also bei tibber geht es auch weiter. Ist also nur ein Fehler bei Entsoe

**Comment by christian1980nrw** [comment]
> Wenn bei Entsoe keine Preise für Morgen gibt wird abgebrochen und nicht wie bei aWATTar ohne diese Preise weiter gemacht. Tibber kann ich nicht sagen wie sich der verhält, da waren Preise da.
> 
> Das schlechte bei so einen Abbruch ist das alles was läuft weiter läuft.
> 
> Vielleicht kannst Du das checken. Ich bin zwar schon Munter weil ich MotoGP schau komme aber wahrscheinlich erst wieder am Nachmittag dazu mir was anzuschauen.
> 
> Ich habe sicherheitshalber einen älteren code getestet, der macht das auch. Nur um sicher zu gehen das ich da nix vermurkst habe als ich den Code umsortiert habe. (aktuelles dev)
> 
> lg Chris

Ich habe nur nachmittags getestet, kann sein das mir das entgangen ist.

**Comment by christian1980nrw** [comment]
Fehler behoben mit https://github.com/christian1980nrw/Spotmarket-Switcher/commit/c16944b79111607c8c0ea8c3f0e3b5c440da3846
