### ISSUE TITLE
Switchable sockets maybe will not be turned on at lowest prices

### ISSUE THREAD

**Issue by christian1980nrw** [christian1980nrw/Spotmarket-Switcher#148]
@ckvsoft Maybe we have overseen a bigger issue. I noticed that the economy check is done correctly and charging is cancelled but i also noticed that the switchable sockets will not be turned on anymore. They should not be affected by the economy check because there are no charging losses. The lowest price today will be at 23:00, i will verify it again.

**Comment by ckvsoft** [comment]
Glaub das war execute_switchablesockets statt execute_switchablesockets_on
Ein Schreibfehler beim check

**Comment by christian1980nrw** [comment]
fixed with https://github.com/christian1980nrw/Spotmarket-Switcher/pull/150
