### ISSUE TITLE
Feature Request: Custom API for energy consumer devices

### ISSUE THREAD

**Issue by Karkas66** [christian1980nrw/Spotmarket-Switcher#178]
Can you implement a logic to switch on devices via custom api (RESTfull) like the [iobroker simple API](https://github.com/ioBroker/ioBroker.simple-api). You just need to call a simple URL like this:

`http://ipaddress:8087/set/javascript.0.test?value=1`

So if you set some variables in the config like...

```
use_custom_api=1
custom_api_base_url="http://ipaddress:8087/set/javascript.0.test?value="
custom_api_on_value="1"
custom_api_off_value="0"
custom_api_username="user"
custom_api_password="pass"
custom_api_return_code="200"
....
```

you get the point...

EDIT: There may be more than one value that you want to change on a single host

**Comment by christian1980nrw** [comment]
Unfortunately no, I don't have such an environment and due to limited available time therefore can't test this.
But you can install this yourself by creating a fork and changing the Shelly implementation, for example.
If you report that it works, I would adopt the modification into the standard.
