### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Feil1** [christian1980nrw/Spotmarket-Switcher#182]
Hallo,
kurze frage bei mir gings jetzt ein paar wochen und seit kurzem krieg ich immer diesen fehler:
/data/etc/Spotmarket-Switcher/controller.sh: line 468: 31: command not found

mfg

**Comment by christian1980nrw** [comment]
Hi, bitte mehr Infos (z.B. genaue Version oder ein vollständiges Log eines Durchlaufes).

**Comment by christian1980nrw** [comment]
No details received. Will be closed.
